import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath, URL } from "node:url";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  build: {
    outDir: "build",
    /* MULTI-PAGE BUILD. The subpages are real pages of this app, not files a
       Node script writes afterwards.

       They used to be generated by `scripts/legal-pages.mjs` and
       `scripts/about-page.mjs`, which had to hand-write their own CSS:
       Tailwind only scans `index.html` and `src/**\/*.{ts,tsx}`, so a utility
       class typed into a `.mjs` file is purged and silently does nothing.
       That forced every subpage to re-implement the design by hand, and the
       re-implementation drifted from the real one — which is exactly what the
       client kept seeing and calling out.

       Listing them as Rollup inputs removes the cause: each page is a normal
       Vite entry, its component lives in `src/` where Tailwind can see it, and
       it imports the same Header, Footer and reveal components the home page
       does. There is no second copy of the design left to drift. */
    rollupOptions: {
      input: {
        main: fileURLToPath(new URL("./index.html", import.meta.url)),
        about: fileURLToPath(new URL("./ueber-uns/index.html", import.meta.url)),
        analyse: fileURLToPath(new URL("./analyse/index.html", import.meta.url)),
        imprint: fileURLToPath(new URL("./impressum/index.html", import.meta.url)),
        privacy: fileURLToPath(new URL("./datenschutz/index.html", import.meta.url)),
        terms: fileURLToPath(new URL("./agb/index.html", import.meta.url)),
      },
    },
  },
  /* `vite preview` rejects any Host header it does not recognise, which blocks
     tunnelled hostnames (loca.lt, trycloudflare, ngrok …) with a 403. This is
     a LOCAL PREVIEW server only — it never runs in production, where the build
     output is served as static files by the host — so allowing any host here
     costs nothing and makes phone testing over a tunnel work. */
  preview: {
    allowedHosts: true,
  },
});
