/**
 * IndexNow submission — the one indexing lever that needs no account.
 *
 * WHY THIS EXISTS. Diagnosing "why doesn't any AI engine cite us", the root
 * cause was not the on-page markup (JSON-LD, llms.txt, the noscript
 * fallback were all already correct) — it was that `site:leadsengine.ch`
 * returns ZERO results on Google, and the domain has never been crawled by
 * the Internet Archive either. A retrieval-based answer engine (Perplexity,
 * Bing Copilot, Google AI Overviews) can only cite a page that is already in
 * the search index it draws from; no amount of on-page schema fixes an empty
 * index entry.
 *
 * Submitting through Google Search Console is the normal fix, but it needs
 * an account this session does not have. IndexNow is the one channel that
 * needs neither an account nor a login: any host can push a URL list to
 * api.indexnow.org, proven by a key file hosted on the domain itself, and
 * Bing (which several AI engines draw from) picks it up directly.
 *
 * THE KEY FILE. `frontend/public/<key>.txt` must contain exactly the key,
 * nothing else, at the domain root — that file IS the ownership proof, so it
 * ships in the same build as everything else and is live before this script
 * ever runs.
 *
 * Run after a deploy that changed a page's content, not on every build —
 * IndexNow is a "this changed, please re-fetch it" signal, not a health
 * check.
 *
 *     node scripts/indexnow.mjs
 */
const HOST = "leadsengine.ch";
const KEY = "e205dd3b5312fdbc53bcaae385abe941";
const KEY_LOCATION = `https://${HOST}/${KEY}.txt`;

/* Every URL worth a crawler's attention today. Kept as an explicit list
   rather than parsed out of sitemap.xml — the sitemap is generated by
   scripts/seo.mjs from build-time file mtimes, which is the right source of
   truth for lastmod but adds a build dependency this script does not
   otherwise need. Add a line here when a page is added there. */
const URLS = [
  "",
  "analyse/",
  "ueber-uns/",
  "wissen/",
  "wissen/was-ist-geo/",
  "impressum/",
  "datenschutz/",
  "agb/",
].map((path) => `https://${HOST}/${path}`);

/**
 * ONLY SUBMIT URLS THAT ARE ACTUALLY LIVE.
 *
 * This list and the deploy can disagree, and did: `/wissen/` was re-enabled
 * in the repo while the build holding it was deliberately not shipped, so
 * this script was one `npm run deploy` away from telling Bing to fetch two
 * URLs that answer 404. That is worse than not pinging at all — IndexNow is
 * a trust-weighted channel, submissions are scored against what the crawler
 * finds, and a host that announces dead URLs gets its later submissions
 * taken less seriously. The one thing this script exists to buy is exactly
 * that credibility.
 *
 * So each URL is fetched first. HEAD would be cheaper, but shared hosts
 * routinely answer it differently from GET, and a wrong answer here silently
 * drops a real page from the submission — so it is a GET, discarded.
 */
const checks = await Promise.all(
  URLS.map(async (url) => {
    try {
      const r = await fetch(url, { redirect: "manual" });
      return { url, status: r.status, live: r.status === 200 };
    } catch (err) {
      return { url, status: `unreachable (${err.message})`, live: false };
    }
  }),
);

const live = checks.filter((c) => c.live).map((c) => c.url);
const dead = checks.filter((c) => !c.live);

for (const d of dead) {
  console.warn(`IndexNow: skipping ${d.url} — ${d.status}`);
}

if (live.length === 0) {
  console.error("IndexNow: no live URLs to submit. Nothing sent.");
  process.exit(1);
}

const res = await fetch("https://api.indexnow.org/indexnow", {
  method: "POST",
  headers: { "Content-Type": "application/json; charset=utf-8" },
  body: JSON.stringify({
    host: HOST,
    key: KEY,
    keyLocation: KEY_LOCATION,
    urlList: live,
  }),
});

/* IndexNow returns 200 or 202 on success, with an empty body either way —
   there is no confirmation payload to parse, only the status code. */
console.log(
  `IndexNow: HTTP ${res.status} for ${live.length} live URL(s)` +
    (dead.length ? `, ${dead.length} skipped` : ""),
);
if (res.status !== 200 && res.status !== 202) {
  const body = await res.text().catch(() => "");
  console.error("IndexNow submission did not succeed:", body.slice(0, 300));
  process.exitCode = 1;
}
